branch-defaults:
  master:
    environment: worker-scooters
    group_suffix: scooters
environment-defaults:
  Roller-dev2:
    branch: null
    repository: null
global:
  application_name: scooters
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.7
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
