# Generated by Django 2.1.10 on 2019-07-12 20:37

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTrackingArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('area', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='crawler',
            field=models.CharField(choices=[('circ', 'vehicles.crawlers.circ.CircCrawler'), ('emmy', 'vehicles.crawlers.emmy.EmmyCrawler'), ('hive', 'vehicles.crawlers.hive.HiveCrawler'), ('lime', 'vehicles.crawlers.lime.LimeCrawler'), ('tier', 'vehicles.crawlers.tier.TierCrawler'), ('ufo', 'vehicles.crawlers.ufo.UfoCrawler'), ('voi', 'vehicles.crawlers.voi.VoiCrawler'), ('zero', 'vehicles.crawlers.tier.ZeroCrawler')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='settings',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}', verbose_name='configuration attributes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicetrackingarea',
            name='service_providers',
            field=models.ManyToManyField(to='vehicles.ServiceProvider'),
        ),
    ]
