# Generated by Django 2.1.10 on 2019-07-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_auto_20190712_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='crawler',
            field=models.CharField(choices=[('vehicles.crawlers.circ.CircCrawler', 'circ'), ('vehicles.crawlers.emmy.EmmyCrawler', 'emmy'), ('vehicles.crawlers.hive.HiveCrawler', 'hive'), ('vehicles.crawlers.lime.LimeCrawler', 'lime'), ('vehicles.crawlers.tier.TierCrawler', 'tier'), ('vehicles.crawlers.ufo.UfoCrawler', 'ufo'), ('vehicles.crawlers.voi.VoiCrawler', 'voi'), ('vehicles.crawlers.tier.ZeroCrawler', 'zero')], max_length=50, null=True),
        ),
    ]
