# Generated by Django 2.1.10 on 2019-07-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehiclelocationtrack_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelocationtrack',
            name='last_seen',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='vehiclelocationtrack',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
