# Generated by Django 2.2.3 on 2019-07-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_auto_20190712_2159'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vehiclelocationtrack',
            constraint=models.UniqueConstraint(fields=('vehicle', 'position', 'last_seen'), name='unique-user-short-ref'),
        ),
    ]
