# Generated by Django 2.2.3 on 2019-07-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_auto_20190713_0643'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vehiclelocationtrack',
            name='unique-user-short-ref',
        ),
        migrations.AddConstraint(
            model_name='vehiclelocationtrack',
            constraint=models.UniqueConstraint(fields=('vehicle', 'last_seen'), name='unique-user-short-ref'),
        ),
    ]
