# Generated by Django 2.2.3 on 2019-07-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_auto_20190713_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclelocationtrack',
            name='updated_at_day',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('vehicle_id',), name='unique-vehicle-id'),
        ),
        migrations.AddConstraint(
            model_name='vehiclelocationtrack',
            constraint=models.UniqueConstraint(fields=('vehicle', 'position', 'battery_level', 'updated_at_day'), name='unique-vehicle-position-battery'),
        ),
    ]
