# Generated by Django 2.2.3 on 2019-07-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0009_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripestimation',
            name='price_estimation',
            field=models.DecimalField(decimal_places=3, max_digits=7, null=True),
        ),
    ]
