# Generated by Django 2.2.3 on 2019-07-13 09:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_tripestimation_price_estimation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripestimation',
            name='route_estimation',
            field=django.contrib.gis.db.models.fields.LineStringField(null=True, srid=4326),
        ),
    ]
