# Generated by Django 2.2.3 on 2019-07-13 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0013_auto_20190713_1506'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vehiclelocationtrack',
            name='unique-user-short-ref',
        ),
        migrations.RemoveConstraint(
            model_name='vehiclelocationtrack',
            name='unique-vehicle-position-battery',
        ),
        migrations.RemoveIndex(
            model_name='vehiclelocationtrack',
            name='vehicles_ve_vehicle_519caa_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehiclelocationtrack',
            name='vehicles_ve_vehicle_e3cf8f_idx',
        ),
        migrations.RemoveField(
            model_name='tripestimation',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='vehiclelocationtrack',
            name='vehicle',
        ),
    ]
