# Generated by Django 2.2.3 on 2019-07-13 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0014_auto_20190713_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripestimation',
            name='vehicle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='vehicles.Vehicle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclelocationtrack',
            name='vehicle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='location_track', to='vehicles.Vehicle'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='vehiclelocationtrack',
            index=models.Index(fields=['vehicle'], name='vehicles_ve_vehicle_519caa_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclelocationtrack',
            index=models.Index(fields=['vehicle', 'updated_at'], name='vehicles_ve_vehicle_e3cf8f_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehiclelocationtrack',
            constraint=models.UniqueConstraint(fields=('vehicle', 'last_seen'), name='unique-user-short-ref'),
        ),
        migrations.AddConstraint(
            model_name='vehiclelocationtrack',
            constraint=models.UniqueConstraint(fields=('vehicle', 'position', 'battery_level', 'updated_at_day'), name='unique-vehicle-position-battery'),
        ),
    ]
