# Generated by Django 2.2.3 on 2019-07-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0016_tripestimation_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='primary_color',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='text_color',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
