# Generated by Django 2.2.3 on 2019-07-14 07:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0017_auto_20190713_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubUrb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('avg_income', models.IntegerField()),
                ('area', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('service_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.ServiceTrackingArea')),
            ],
        ),
    ]
