# Generated by Django 2.2.3 on 2019-07-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0018_suburb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suburb',
            name='avg_income',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='suburb',
            name='population',
            field=models.IntegerField(null=True),
        ),
    ]
