# Generated by Django 2.2.3 on 2019-07-14 07:36

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0020_auto_20190714_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suburb',
            name='area',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
