# Generated by Django 2.2.3 on 2019-07-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0022_vehiclelocationtrack_suburb'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripestimation',
            name='route_distance_estimation',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tripestimation',
            name='route_duration_estimation',
            field=models.DurationField(null=True),
        ),
    ]
