# Generated by Django 2.2.3 on 2019-07-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0023_auto_20190714_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suburb',
            name='avg_income',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='suburb',
            name='population',
            field=models.BigIntegerField(null=True),
        ),
    ]
