# Generated by Django 2.2.3 on 2019-07-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0025_auto_20190714_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripestimation',
            name='trip_type',
            field=models.CharField(choices=[('SHORT_TRIP', 'short area trip; less than 5km'), ('LAST_MILE_TRIP', 'short area trip; start or ends at a station'), ('FUN_TRIP', 'a trip that probably just out of curiosity or by tourists'), ('UNCLASSIFIED', 'not classified'), ('UNKNOWN', 'hmm?!')], default='UNCLASSIFIED', max_length=100),
        ),
    ]
