# Generated by Django 2.2.3 on 2019-07-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0026_tripestimation_trip_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripestimation',
            name='trip_type',
            field=models.CharField(choices=[('SHORT_TRIP', 'short area trip; usually less than 5km'), ('LONG_TRIP', 'long trips; usually more than 5km'), ('LAST_MILE_TRIP', 'short area trip; start or ends at a station'), ('FUN_TRIP', 'a trip that probably just out of curiosity or by tourists'), ('UNCLASSIFIED', 'not classified'), ('UNKNOWN', 'hmm?!')], default='UNCLASSIFIED', max_length=100),
        ),
        migrations.AlterField(
            model_name='tripestimation',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
