# Generated by Django 2.2.3 on 2019-07-15 15:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0028_auto_20190715_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelocationtrack',
            name='suburb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='vehicles.SubUrb'),
        ),
        migrations.CreateModel(
            name='PublicTransportStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('service_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='vehicles.ServiceTrackingArea')),
            ],
        ),
        migrations.AddField(
            model_name='vehiclelocationtrack',
            name='public_transport_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='vehicles.PublicTransportStation'),
        ),
    ]
