# Generated by Django 2.2.3 on 2019-07-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0030_auto_20190715_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclelocationtrack',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclelocationtrack',
            name='updated_at_day',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
