# Generated by Django 2.2.3 on 2020-03-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0032_auto_20190715_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='free_minutes',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='crawler',
            field=models.CharField(choices=[('vehicles.crawlers.circ.CircCrawler', 'circ'), ('vehicles.crawlers.emmy.EmmyCrawler', 'emmy'), ('vehicles.crawlers.hive.HiveCrawler', 'hive'), ('vehicles.crawlers.lime.LimeCrawler', 'lime'), ('vehicles.crawlers.tier.TierCrawler', 'tier'), ('vehicles.crawlers.ufo.UfoCrawler', 'ufo'), ('vehicles.crawlers.voi.VoiCrawler', 'voi'), ('vehicles.crawlers.tier.ZeroCrawler', 'zero'), ('vehicles.crawlers.call_a_bike.CallABikeCrawler', 'call_a_bike')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tripestimation',
            name='trip_type',
            field=models.CharField(choices=[('SHORT_TRIP', 'short area trip; usually less than 5km'), ('LONG_TRIP', 'long trips; usually more than 5km'), ('FUN_TRIP', 'a trip that probably just out of curiosity or by tourists'), ('UNCLASSIFIED', 'not classified'), ('DEPLOYMENT', 'deployment of scooter'), ('UNKNOWN', 'hmm?!')], default='UNCLASSIFIED', max_length=100),
        ),
    ]
