# Generated by Django 2.2.16 on 2020-09-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0034_tripestimation_route_timing'),
    ]

    operations = [
        migrations.CreateModel(
            name='PingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
