# Generated by Django 2.2.16 on 2020-09-27 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0035_pingmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PingModel',
        ),
    ]
