# Generated by Django 2.2.16 on 2020-09-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0037_receivedsms'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('scooter', 'Scooter'), ('emoped', 'E-Moped'), ('bicycle', 'Bicycle')], default='scooter', max_length=30),
        ),
    ]
