# Generated by Django 2.2.16 on 2020-09-28 12:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0039_auto_20200928_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubUrb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('population', models.BigIntegerField(null=True)),
                ('avg_income', models.BigIntegerField(null=True)),
                ('area', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('service_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.ServiceTrackingArea')),
            ],
        ),
        migrations.AddField(
            model_name='vehiclelocationtrack',
            name='suburb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='vehicles.SubUrb'),
        ),
    ]
