branch-defaults:
  master:
    environment: roller-server
    group_suffix: dev
environment-defaults:
  Roller-server:
    branch: null
    repository: null
  Scooters-env:
    branch: null
    repository: null
  roller-worker:
    branch: null
    repository: null
global:
  application_name: Roller
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.7
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
